package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynSequence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-8-wnL82d/openjdk-8-8u171-b11/src/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Friday, April 27, 2018 5:19:46 PM UTC
*/


/**
    * DynSequence objects support the manipulation of IDL sequences.
    */
public interface DynSequence extends DynSequenceOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynSequence
