package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynValueCommon.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-8-wnL82d/openjdk-8-8u171-b11/src/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Friday, April 27, 2018 5:19:46 PM UTC
*/


/**
    * DynValueCommon provides operations supported by both the DynValue and DynValueBox interfaces.
    */
public interface DynValueCommon extends DynValueCommonOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynValueCommon
