package org.omg.IOP;


/**
* org/omg/IOP/TAG_POLICIES.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-8-wnL82d/openjdk-8-8u171-b11/src/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Friday, April 27, 2018 5:19:46 PM UTC
*/

public interface TAG_POLICIES
{

  /**
       * A profile component containing the sequence of QoS policies exported
       * with the object reference by an object adapter.
       */
  public static final int value = (int)(2L);
}
